### ISSUE TITLE
Webtools v2.2/v2.3

### ISSUE THREAD

**Issue by Blahblah44** [ukdtom/WebTools.bundle#250]
The webtools v.2 & v.3 isn't working for me/ I keep getting an error code.

**Comment by creoludifico** [comment]
V3 is not published yet. It's not even in alpha stage :-)

For V2 we need you to supply us with the log files.
If you are using a Windows platform the default directory for the log files is here.
C:\Users\[USER]\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.plugins.WebTools.log

**Comment by creoludifico** [comment]
Hello Blahblah44

Could you provide us with the log files?
You can find them under the following directory if you are using a windows platform

PMS log file:
C:\Users\(USERNAME)\AppData\Local\Plex Media Server\Logs\Plex Media Server.log

WebTools log file:
C:\Users\(USERNAME)\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.plugins.WebTools.log

**Comment by ukdtom** [comment]
And adding here....Stay away from V3!

Only use V2.3, found in the release here:
https://github.com/ukdtom/WebTools.bundle/releases/latest

And the links that @creoludifico provided, only goes if on Windows platform, and the limited info you provided us with so far, makes this kinda impossible, since you don't even tell us what you see :-1:

**Comment by ukdtom** [comment]
@Blahblah44 Ping....

**Comment by ukdtom** [comment]
Closed due to lack of response
