### ISSUE TITLE
Subs upload

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#330]
Icon there, but MIA codebehind?

**Comment by creoludifico** [comment]
Is it possible for you to change the API?
I don't see why the frontend needs to know what the movie path is. 
So instead of having to call you with the "remoteFile" i could just call you with the following URL as POST:
"api/v3/pms/uploadFile/key/[EPISODE/MOVIE KEY]"
And in the databody there will be a file in the param localFile

Then you find the folder in backend, place the file and return true/false :1st_place_medal:

**Comment by ukdtom** [comment]
I hate you !

**Comment by creoludifico** [comment]
:butterfly:

**Comment by ukdtom** [comment]
You ain't going to like this, since it's complicated for the front-end ;)
But check the docs for uploadSub method

**Comment by creoludifico** [comment]
Damn 😢

**Comment by creoludifico** [comment]
I finally got something done with this one.

The upload dialog will close after successfully upload - this is the solution for now because there were some challenges with the ngDialog plugin.

**Comment by ukdtom** [comment]
Sadly not okay :(

For the language selection box, you are calling `api/v3/wt/getLanguageList`

That only returns a list of translated languages, but if like Russian is not yet translated, we still want people to be able to upload Russian subs.

Instead, call `/api/v3/language/getLangCodeList`

**Comment by ukdtom** [comment]
Besides that, looks great

**Comment by creoludifico** [comment]
Done

**Comment by ukdtom** [comment]
Perfect
