### ISSUE TITLE
Discussion: prevent user confusion by not calling Plug-Ins "Apps"

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#356]
Even though it is such a nice abbreviation `UAS`
and the term `app store` is almost ubiquitous nowadays:

Do we really want to call "app", what is already known in Plex web and all of the official documentation as "Plug-In" or "Channel" ?

I want to prevent confusion for end users (and also prevent more support questions from confused users ;) ).

I propose we need to think hard about that.
And then eventually remove all references to "apps" from WebTools...

**Comment by ukdtom** [comment]
So far, we have two strings where the word "App" is part of, and that's during migration

I see the point here in maybe changing that to "Channels/Plug-ins"
(Using both names then works for a regular channel, as well as agents and my small collection of tools)

However, changing the full and short name for UAS is IMHO a No-Go, since that's already part of the Plex Universe mindset, IMHO, and been that way since the first UAS was made

So thoughts here?

**Comment by ukdtom** [comment]
And since I just added the translation strings for that, we should then react fast, before new translators chime in, in order to not vaste their work

**Comment by OttoKerner** [comment]
Agreed, the name `UAS` doesn't need to be changed.
But all other mentions of "apps" need to.

**Comment by ukdtom** [comment]
Agreed.

@creoludifico We need to change uasservice.js strings:
        `appsMigrated: gettext("Apps migrated:"),
        noAppsMigrated: gettext("No apps was migrated:")`
Into:
        `appsMigrated: gettext("Channel/Plug-ins migrated:"),
        noAppsMigrated: gettext("No Channel/Plug-in was migrated")`

Also note the noAppsMigrated I skipped the trailing colon?

**Comment by OttoKerner** [comment]
plural: "No apps were migrated:" ;-)
