### ISSUE TITLE
UAS v3 'update' option is incorrectly offered for unsupported plugins

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#358]
These plugins were probably incorrectly 'migrated' previously.

![update](https://user-images.githubusercontent.com/10280992/29041855-bdd2fa56-7bb4-11e7-8bba-f42b15f11675.jpg)

**Comment by ukdtom** [comment]
You are correct here :(

@creoludifico 

When reaching for the endpoint `api/v3/git/list` and look on the keys....

If a key starts with `https://github.com/` then the update option should be present, and else it should not, since if not, it indicate a channel/plug-in, that was migrated in, and we don't know a Repo

**Comment by creoludifico** [comment]
R4Test

**Comment by ukdtom** [comment]
Perfect.
@OttoKerner I'll ping you, when a new translate build is ready for testing

**Comment by OttoKerner** [comment]
This issue appears to be resolved.
