### ISSUE TITLE
WTv3 - At startup - Translations must be manually updated

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/WebTools.bundle#370]
When you first open WT all translated strings show with [!] indicating they have not been updated. You must then go to Languages and force an update.

Could that be made automatic, so that when WT is first opened, it automatically updates the translations?

**Comment by ukdtom** [comment]
It could, but not something we will do, since I do not want all installed versions of WT to hit the translation site during each launch.

When we release in public, WT will be pre populated with the translations in their current state, and as such I hope, that it only would be used rarely, and when new languages gets translated after we release.

We do however plan to host a public Beta, where beta testers also will be asked to translate, and as such, expect that WT would cover at least 15 languages when released. (Currently covers 10)

Also note, that the [!] indicator is only during Alpha/Beta testing, to help out with the initial translation.
When released, if a string is missing, it'll simply show the build in instead
