### ISSUE TITLE
playlists: when copying smart playlists with 'watched' criteria, adapt user ID

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#374]
I created a smart playlist which combines 3 tv shows in the same universe (Arrow, Supergirl, The Flash).
I also included a condition 'Watched=0'
That way, one can watch these shows in-order, including the crossover episodes.

When copying this smart playlist to a different user, the 'Watched' condition still uses **my** watched status.
Instead of the 'watched' status of the target user, to which the playlist is copied.

The question is: should this ID get adapted to the new user or not?
I can imagine some use cases where it is desirable 
and some use cases where it is not desirable.

Maybe it is time for an additional switch 'adapt smart playlists to target user'?

**Comment by ukdtom** [comment]
That part is out of WebTools hands, and a pure PMS issue, since we do not copy the watched status, only the key of the media!

And regarding SmartLists, as soon as they are copied, they end up @ the target user as dumb static lists, since the API sadly has no way of exporting the query behind a smartlist :(
