### ISSUE TITLE
Allow for server IP in WebTools' Plex Channel view instead of 127.0.0.1 in URL

### ISSUE THREAD

**Issue by WolfganP** [ukdtom/WebTools.bundle#379]
While using Plex webui on a remote machine, exploring WebTools channel shows:

```
To access this channel, type the url's below to a new browser tab
http://127.0.0.1:33400
http://127.0.0.1:33443
```
Would it be possible to build the URL with the server address instead (ie 192.168.1.50) and make it clickable to a new tab? (or if auto URL build is not possible, allow a config field to replace 127.0.0.1 by an user entered IP in the config page)
Thx.

**Comment by trumpy81** [comment]
You are able to use your server's IP address by manually typing it into your browser (http://Your-Server-IP:33400), however, a clickable link in Plex channels->WebTools is not possible due to a security restriction in the Plex api.

After using your server IP address in your browser, create a bookmark in your browser, to save you having to type it in again.
