### ISSUE TITLE
[REQ] Mass select all subtitles

### ISSUE THREAD

**Issue by Nottt** [ukdtom/WebTools.bundle#383]
It would be very nice if we could mass select all subtitles that can be selected in a library to either delete/download them. 

Having to do this manually is driving me crazy! Thanks for this wonderful tool however.

**Comment by ukdtom** [comment]
Since we do not pull down that info in one go, but instead use a paged req, in order not to drain the PMS, this is currently not durable.

When that's said, I created this #384 GHI, but it'll sadly not make it for the next release, since we are too close to that.

**Comment by Nottt** [comment]
I don't care about draining my PMS, just pull all the stuff and let me select in one go :) 

But thanks for adding it, it will be added to next releases then ?

**Comment by ukdtom** [comment]
No idea yet...It's a matter of usecase

Slated for 3.1.0, but only time will tell, and depends on what's popping up as new ideas....
We are only two devs, one for front-end, and one for back-end, so time is sadly not on our side, since this is done in our spare time, and we are always going for the most wanted ;)

**Comment by Nottt** [comment]
My ideia servers a lot of usecases, you may want to download all subtitles downloaded by their metadata agents, one may want to delete them all after doing that. 

OpenSubtitles has a 200 subs/day limit so for people with big libraries you don't want to restart from 0

**Comment by ukdtom** [comment]
I fully understand here, and your point is noticed!
But it's all about prioritize, and what is the use case for you, might not be for others.
Do consider the fact, that we respond to a lot of users here, and the current release has +102.000 downloads!
And when talking about prioritize, simply covering the forums, and supporting users of WT, is draining us, leaving less time to development.

But when said...

Within the next 3-4 weeks, we do expect a public beta of WT V3.
Beta users do have our ears ;)
So do stay tuned in to the Plex forum thread, in order to join our Beta, when announced 

Best Regards

Tommy
