### ISSUE TITLE
Stuck at login screen

### ISSUE THREAD

**Issue by skyleet** [ukdtom/WebTools.bundle#405]
## Environment
- **Windows 10 Pro x64 build 15063.608**: 
- **PMS Version**: 
- **Chrome**: 

## Error shown
- **Stuck at login screen with spinnng gear**: 

## Steps to reproduce
1. 

## Expected behaviour
1. 

## Actual behaviour
1. 

## Checklist
- [ ] Listed environment
- [ ] Included PMS log zip and WebTools log
- [ ] Included screenshots (where appropriate)
- [ ] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
Logs please....
PMS Version....
Browser version.....

**Comment by skyleet** [comment]
Thanks, Got it 
I first logged in in Firefox and then it worked in chrome.
PMS - Version 1.9.2.4285 (Sorry didn't know what's PMS)

**Comment by ukdtom** [comment]
Plex Media Server ;)

**Comment by ciaron88** [comment]
Hi 

I am also getting this issue on my Synology. 

## Environment
- **PMS Platform(s) OS**: 
Synology DS918+ DSM 6.2.1-23824 Update 6
- **PMS Version**:  
1.14.1.5488-cc260c476
- **Name of Browser**: 
Firefox and Chrome

## Error shown
- **Symptom**: 
Stuck on login screen with spinning cog

## Steps to reproduce
1. go to "server ip":33400/login
2. enter Plex account details
3. click Sign In

## Expected behaviour
1.  WebTools is logged in to and shown

## Actual behaviour
1. Infinite spinning cog

## Logs
[com.plexapp.plugins.WebTools.log](https://github.com/ukdtom/WebTools.bundle/files/2970698/com.plexapp.plugins.WebTools.log)
[Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/2970694/Logs.zip)

**Comment by ukdtom** [comment]
@ciaron88 

Issue was closed, but reopening ;)

Your logs indicate no errors, so small Q here:
Are you using native plex.tv logon, or perhaps like google auth?

Cuz. if so, look here:
https://github.com/ukdtom/WebTools.bundle/wiki/FAQ#Q8

**Comment by ciaron88** [comment]
Hi

I am using Plex.tv logon details

**Comment by ukdtom** [comment]
Then please try another browser, since seen some AntiVira/popup blockers has prevented auth in the past

**Comment by ciaron88** [comment]
Sorry i was putting in my email and not my Plex Username. works now

Thanks a lot for the help

**Comment by ByteKnight-zz** [comment]
If you have Bitdefender then check your logs - this is the second time it blocked unencrypted passwords on me - Bitdefender also doesn't tell you it blocked your login!
