### ISSUE TITLE
UAS and counters

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#463]
Somethings wrong here with the installed counter for all...

Look at this screenshot

![uas-counter](https://user-images.githubusercontent.com/4699449/34018535-8dc2fdda-e12a-11e7-9aed-72995ce473e5.png)

The installed counter is correct, and I went into the category, and counted all green ones, and it added up to the number in the installed category (17), yet it says 20

**Comment by creoludifico** [comment]
And you are sure it's not you returning a weird number from backend? See screenshots
![image](https://user-images.githubusercontent.com/12425208/34079118-24c56c2e-e327-11e7-864c-7b77e36a3e55.png)

![image](https://user-images.githubusercontent.com/12425208/34079121-4576c288-e327-11e7-896b-b8b5d0cbad48.png)

**Comment by ukdtom** [comment]
100% sure here, since you calculate the counter ;-)

And might be caused by the fact, that some bundles can belong to more than one category?

**Comment by creoludifico** [comment]
I count for the custom category installed.
Here the counter is 3 and i have 3 installed so that must be correct
![image](https://user-images.githubusercontent.com/12425208/34083673-812bb3e0-e374-11e7-92a2-e1faa3df3ddd.png)

I can find the exact same bundles installed under the category "All" but here the counter only says 2.
I dont count for the categoriy All. I just use the number you return to me?

**Comment by creoludifico** [comment]
The Shoutcase2017 is messing things up here.

**Comment by ukdtom** [comment]
Sadly confirmed to be a backend issue :(

**Comment by ukdtom** [comment]
Fixed with above commit
