### ISSUE TITLE
Playlist copy to all and self

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#464]
Select a playlist, and copy to all users

Ref: https://forums.plex.tv/discussion/comment/1575416/#Comment_1575416

**Comment by ukdtom** [comment]
UserTo should be set to "All", in case you wanna copy playlist to all users on the PMS.

As such, GUI should allow that option, and pass it along to backend

**Comment by ukdtom** [comment]
And in the Doc

**Comment by creoludifico** [comment]
Maybe you could fix this from the backend by returning another user called "All" to the user list. 
If the copy button is clicked with this user selected you will know directly in the backend.

**Comment by ukdtom** [comment]
Been rethinking here, and has to be done in the frontend, since we do not want it in the Source combo

**Comment by creoludifico** [comment]
Been rethinking here, and i think it would be smart to do it in backend and then i'll filter out the key "All" for source combo

**Comment by ukdtom** [comment]
Fear we might use the call in the future for lots of things, so fail to see why not add it in front-end on demand, like you did with `-- self --` ?

But not totally declining a back-end solution here, just fear it'll bite us later on, since only front-end knows when needed or not

**Comment by creoludifico** [comment]
1)
You got a point but we can avoid that future problem.

If you extend the current GetUsers call with an include paramter i can then use that call for whatever i need in frontend. 
You have multiple solutions for the filter. I'm thinking of using a flag (bit) filter like this:
?include=0 or no paramter //Returns only users
?include=1 //Returns users and self
?include=2 //Returns users and all
?include=3 //Returns users, self and all
I'll make an enum frontend for easy reading and you could - if python support it - do that too in backend. If it doesnt support enums it should somehow support directly passing of bits?

2) If i fix this in frontend by adding All and Self i'll have to hardcode some ID's and you will have to take care of these. A reason to why it's very simple now is because of id is equal to null in Self.
Furthermore the copy backend call right now doesnt support null calls. By solution 1) i dont have to take care of some hardcoded ids and i dont have to manipulate a list received from you.

**Comment by AtumVirt** [comment]
Very much excited to see this feature coming...I have a family of 5 + guest...copying dozens of playlists ... is... better than without webtools for certain but this will make it better :)
