### ISSUE TITLE
Primary Agent Changer

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#509]
Case:
If you decide to change the Primary Agent for a Library, it'll only work for new items in the Library
There's no way to change primary agent for items already present in the library

Solution:
WT should scan all items, and update the agent used if needed

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts

**Comment by camjac251** [comment]
Have you used this feature since the hold on development to WebTools? I've tried to follow the Docs on the API to get it to work since there wasn't a page for it that I could see. That didn't seem to work for me sadly, I had some issues with authentication.

I was just curious if you did use it, if I could ask what commands you ran on the api to do so since I have a serious problem with missing metadata on my library due to the omdb agent discontinuing long ago.

**Comment by ukdtom** [comment]
Dev stopped almost 2 years ago, and was left in a state I sadly can't remember regarding this, but wasn't finished!

As such, I urge you to use ExportTools instead, to maybe track down agent used for a media, and the do the Plex Dance on those

**Comment by camjac251** [comment]
I have way too many shows/movies that are using older agents or non-existent ones. The Plex Dance is an option but not without its caveats. Mainly losing all history for every user being one of them, unless that's changed. The watch status would change completely. Also if I'm not mistaken, doesn't the plex dance require all library items to be moved to a new location and Plex to refresh the library and empty to work?

**Comment by ukdtom** [comment]
Correct, but sadly all I can think of, besides a manual fix one item a time
