### ISSUE TITLE
NAS WD Compatibility

### ISSUE THREAD

**Issue by FayzB** [ukdtom/WebTools.bundle#518]
## Environment
- **PMS Platform(s) OS**: NAS-PR4100
Linux 4.1.13 (#1 SMP Thu Nov 30 19:20:59 CST 2017 Build-gitdf6634a)
- **PMS Version**: 1.13.5.5291

## Error shown
- **Symptom**: Not compatible with NAS from WD Model PR4100

## Additional Info
Hello
Can you make it compatible with Western Digital NAS?
I have the model PR4100 I installed the plugins but it does not work (it does not even appear in the list)

**Comment by ukdtom** [comment]
Most likely, you installed it wrong, but since I haven't got a WD Device, I can only suggest, that you seek help in the Plex Forums for WD Devices
https://forums.plex.tv/tags/c/plex-media-server/nas-devices/server-western-digital


And this link has a guide
https://forums.plex.tv/t/plugins-instalation/148585/6?u=dane22
