### ISSUE TITLE
Error: var checkIsNewVersionAvailable - Fatal error happened in getReleaseInfo

### ISSUE THREAD

**Issue by syhr0** [ukdtom/WebTools.bundle#526]
## Environment
- **Raspbian GNU Linux 9 (stretch)**: 
- **3.69.1**: 
- **Chromium Version 65.0.3325.181 (Official Build) Built on Raspbian , running on Raspbian 9.6 (32-bit)**: 

## Error shown
![image](https://user-images.githubusercontent.com/44934807/49338322-7e648e00-f617-11e8-9b15-08336b0c13ba.png)

- **Error occurred!

WebTools

Technical Info: 
Url: api/v3/git/getReleaseInfo/url/https%3A%2F%2Fgithub.com%2Fukdtom%2FWebTools.bundle/version/latest
Location: Core
Error: var checkIsNewVersionAvailable - Fatal error happened in getReleaseInfo**: 

## Steps to reproduce
1. Load 127.0.1.1:33400

## Expected behaviour
1. Access to the main page of WebTools

## Actual behaviour
1. A popup appears over the top of the WebTools page.

## Additional Info
[Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/2636837/Logs.zip)

## Checklist
- [Y] Listed environment
- [Y] Included PMS log zip and WebTools log (THIS IS MANDATORY!)
- [Y] Included screenshots (where appropriate)
- [Y] Checked that this isn't already an [issue](https://github.com/ukdtom/WebTools.bundle/issues)

**Comment by ukdtom** [comment]
First of all, you have the wrong owner/rights for the bundle directory!

`2018-12-01 21:41:04,630 (76faa110) :  INFO (wtV3:543) - Updating translation file in storage
2018-12-01 21:41:04,662 (76faa110) :  CRITICAL (wtV3:600) - Exception in createPluginStringTranslations was: [Errno 13] Permission denied: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Strings/en.json' (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Code/wtV3.py", line 595, in createPluginStringTranslations
    with io.open(fileName, 'w', encoding="utf-8") as outfile:
IOError: [Errno 13] Permission denied: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Strings/en.json'
`
Secondly, you are getting http error 403 (Forbidden) when accessing https://api.github.com/repos/ukdtom/WebTools.bundle/releases/latest

Please check from the box that you can do that, and return a json, since it seems like Github is refusing the connection for some reason?

Do you have a proxy in front of it perhaps?

**Comment by syhr0** [comment]
I certainly haven't manually installed a proxy myself. So unless one came installed when I installed Raspbian, I don't have one. I will take a look into permissions. I'll let you know the results.
Thanks for the quick response by the way!

**Comment by syhr0** [comment]
Okay, so I have managed to modify the permissions to give the pi user ownership of the directory. I am now greeted with this error. I've attached an image of the new error, and the logs after making this change.
![image](https://user-images.githubusercontent.com/44934807/49338901-da7fe000-f620-11e8-83dc-9877082f1fa7.png)
[Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/2636847/Logs.zip)

**Comment by ukdtom** [comment]
Still permission errors.....Owner/rights needs to be set to the user running PMS!

`IOError: [Errno 13] Permission denied: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Strings/en.json'`

Also still see access denied from GitHub!

**Comment by syhr0** [comment]
Fantastic, I managed to get it working thanks to your help =D. I'll leave the commands I used in terminal for anyone who may be reading this in the future.
`sudo chown $USER /var/lib/plexmediaserver`
`sudo chown $USER /var/lib/plexmediaserver/Library/"Application Support"/"Plex Media Server"/Plug-ins`
`sudo chown $USER /var/lib/plexmediaserver/Library/"Application Support"/"Plex Media Server"/Plug-ins/WebTools.bundle/Contents/Strings`
`nano /var/lib/plexmediaserver/Library/"Application Support"/"Plex Media Server"/Plug-ins/WebTools.bundle/Contents/Strings/en.json` <--- Used as a test. If your terminal window is filled with a text editor, then you have done it successfully and WebTools will function as usual.

Thanks again for your help. Appreciate it a lot.
